---

- name: apply common configuration to all nodes
  hosts: all

  roles:
    - codewind-bot

  environment:
    AWS_ACCESS_KEY_ID: "{{ aws_access_key_id }}"
    AWS_SECRET_ACCESS_KEY: "{{ aws_secret_access_key }}"
    RESTIC_PASSWORD: "{{ restic_password }}"

