
- import_tasks: ../../shared/tasks/docker.yml

- import_tasks: ../../shared/tasks/shared-setup.yml

# ----------------------------

- name: Install maven and jdk
  apt:
    name: 
      - maven
      - openjdk-8-jdk
    update_cache: yes
  become: true


- git:
    repo: "{{ zham_target_git_repo | default('https://github.com/jgwest/zenhub-api-mirror')}}"
    force: true
    version: "{{ zham_target_git_version | default('master') }}"
    dest: ~/zenhub-api-mirror


- name: Copy file with owner and permissions
  copy:
    src: "{{ lookup('env', 'ZHAM_CONF_YAML_PATH') }}"
    dest: ~/zenhub-api-mirror/ZenHubApiMirrorLiberty/resources/zenhub-settings.yaml
    mode: u=rw,g=r,o=r

  
- name: Run docker build script
  command: ~/zenhub-api-mirror/resources/docker/build.sh


- name: Backup volume to COS (if the volume exists)
  command: ~/shared-scripts/backup-volume-to-cos.sh "zenhub-api-mirror-data-volume" "zham" 
  when:
    - disable_backups is undefined or disable_backups != "true"


- name: If the volume doesn't exist, restore the contents from COS (if COS has at least one backup)
  command: ~/shared-scripts/restore-volume-from-cos.sh "zham" "zenhub-api-mirror-data-volume" "zenhub-api-mirror" "default"


- name: Remove backup to COS crontab if disable_backups is true
  cron:
    name: "Backup ZHAM volume to COS"
    state: absent
  when:
    - disable_backups is defined and disable_backups == "true"


- name: Add cron to backup volume to COS
  cron:
    name: "Backup ZHAM volume to COS"
    hour: "3"
    minute: "12"
    job: "AWS_ACCESS_KEY_ID=\"{{ aws_access_key_id }}\"   AWS_SECRET_ACCESS_KEY=\"{{ aws_secret_access_key }}\"   RESTIC_PASSWORD=\"{{ restic_password }}\" ~/shared-scripts/backup-volume-to-cos.sh zenhub-api-mirror-data-volume zham"
  when:
    - disable_backups is undefined or disable_backups != "true"



- name: Update default exposed port
  lineinfile:
    path: ~/zenhub-api-mirror/resources/docker/run-local.sh
    regexp: ".*9443:9443.*"
    line: "docker run  -d  -p 10443:9443 --name zenhub-api-mirror-container \\"

- name: Run container with Docker
  command: ~/zenhub-api-mirror/resources/docker/run-local.sh

